### ISSUE TITLE
errors when training with different num_classes

### ISSUE THREAD

**Issue by pvmilk** [dougbrion/pytorch-classification-uncertainty#1]
Thank you very much for a nice port of the original repository. 

There is a very minor bugs in the training code when trying to apply the method to other dataset with different num_classes

https://github.com/dougbrion/pytorch-classification-uncertainty/blob/1131535b162edf2b192683376754e4eaffce81d7/train.py#L55

need to replace with 
```
y = one_hot_embedding(labels, num_classes) 
```

**Comment by dougbrion** [comment]
Awesome thanks for spotting this!
